name: Android CI

on:
  push:
    branches: [ "fixed" ]
  pull_request:
    branches: [ "fixed" ]
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 26
      uses: actions/setup-java@v3
      with:
        java-version: '26'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.4
    - name: Releasing and debuging using Hub 
      with:
        path: ./
