name: Android CI

on:
  push:
    branches: [ "fixed" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "fixed" ]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Build
      run: echo ${{ github.sha }} > Release.txt
    - name: Test
      run: cat Release.txt
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
       java-version: '20'
       distribution: 'temurin'
       cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: Release.apk
      env: 
        asset-name: 'release.apk'
        GITHUB_TOKEN: ${{ secrets.token }} 
        APP_FOLDER: app
