name: Android CI

on:
  push:
    branches: [ "fixed" ]
  pull_request:
    branches: [ "fixed" ]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
       java-version: '20'
       distribution: 'temurin'
       cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      
      env: 
        asset-name: 'release.apk'
        GITHUB_TOKEN: ${{ secrets.token }} 
        APP_FOLDER: app
