name: Android CI

on:
  push:
    branches: [ "fixed" ]
  pull_request:
    branches: [ "fixed" ]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21+
      uses: actions/setup-java@v4
      with:
       java-version: '21'
       distribution: 'temurin'
       cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: update release   
      uses: zay448345045/release-apk@main 
      env: 
        GITHUB_TOKEN: ${{ secrets.token }} 
        APP_FOLDER: app
