name: Android CI

on:
  push:
    branches: [ "fixed" ]
  pull_request:
    branches: [ "fixed" ]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 22+
      uses: actions/setup-java@v2
      with:
        java-version: '22.0.1+8'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
