name: Android CI

on:
  push:
    branches: [ "fixed" ]
    
  pull_request:
    branches:
      - fixed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload artifact Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug.apk
          path: '**/*.apk'
    