name: Android CI

on:
  push:
    branches: [ "fixed" ]
    tags:
      - "*"
  
  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Build
      run: echo ${{ github.sha }} > Release.txt
    - name: Test
      run: cat Release.txt
      
      
      
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
       java-version: '20'
       distribution: 'temurin'
       cache: gradle
     - name: Install NDK
       run: echo "y" | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "ndk;27.0.11902837"
     - name: Gradle Build
       uses: gradle/actions/setup-gradle@v3
       env:
         GITHUB_TOKEN: ${{ secrets.token }}
       with:
         arguments: assembleDebug
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: Release.apk
         body: Bump Version
          files: |
            debug-armv8a.apk
      env: 
        asset-name: 'release.apk'
        GITHUB_TOKEN: ${{ secrets.token }} 
        APP_FOLDER: app
