name: Android CI

on:
  push:
    branches: [ "fixed" ]
  pull_request:
    branches: [ "fixed" ]

jobs:
  apk:
    runs-on: ubuntu-latest 
    steps:
    - name: checkout
      uses: actions/checkout@v4
#    - name: Build
     # run: echo ${{ github.sha }} > Release.txt
      
#    - name: Test
     # run: cat Release.txt
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
       java-version: '23'
       distribution: 'temurin'
#       cache#: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: bash ./gradlew assembleDebug 
      

    
    - name: upload apk
      #uses: softprops/action-gh-release@v2
      uses: actions/upload-artifact@v4
   #   if: startsWith(github.ref, 'refs/tags/')
   #   with:
   #       files: debug.apk
   # - name: Upload ARM64
   #   uses: actions/upload-artifact@v4
      with:
          #name: default-arm64-v8a-${{ github.sha }}
          name: apk
          path: '**/*.apk'
          #path: app/build/outputs/apk/default/release/app-default-arm64-v8a-release.apk
#          path: app/build/outputs/apk/debug/app-debug.apk
   #   env: 
    
       #   asset-name: 'debug.apk'
    #       GITHUB_TOKEN: ${{ secrets.token }} 
     #     APP_FOLDER: app
